name: Output Issue Event Details

on:
  issues:
    types: [opened, edited, closed]

jobs:
  debug-issues:
    runs-on: ubuntu-latest

    steps:
      -name Output issue event details
        run:
          echo "Event name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Issue author: ${{ github.event.issue.user.login }}"
          echo "Repository: ${{ github.repository }}"