name: Output Issue Event Details

on:
  issues:
    types: [opened, edited, closed]

jobs:
  debug-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Output issue event details
        run: echo "${{ toJson(github.event) }}"
